// All Duluth Adventures Data (Explore Section)
const allAdventures = [
    {
        id: 'explore-1',
        type: 'adventure',
        name: 'Aerial Lift Bridge',
        category: 'Historic • Landmark • Views',
        cost: 'Free',
        timeNeeded: 'Spend 30-60 Minutes',
        rating: '4.8',
        reviews: '12,456',
        description: 'The iconic symbol of Duluth that lifts to let massive ships enter the harbor.',
        image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 722-4011',
        website: 'https://visitduluth.com/',
        address: '601 S Lake Ave, Duluth, MN 55802',
        highlights: ['Ship Watching', 'Bridge Lifts', 'Night Lights'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-2',
        type: 'adventure',
        name: 'Enger Park',
        category: 'Views • Historic • Gardens',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.7',
        reviews: '8,923',
        description: 'Hilltop park featuring a 5-story stone tower with 360-degree views of the harbor and Japanese gardens.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Central Hillside',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '1601 Enger Tower Dr, Duluth, MN 55806',
        highlights: ['Enger Tower', 'Peace Bell', 'Japanese Garden'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-3',
        type: 'adventure',
        name: 'Canal Park',
        category: 'Tourist Hub • Lake • Dining',
        cost: 'Free',
        timeNeeded: 'Spend 2-4 Hours',
        rating: '4.6',
        reviews: '15,234',
        description: 'The heart of Duluth tourism, featuring the Lakewalk, lighthouse, and shops.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 722-4011',
        website: 'https://canalpark.com/',
        address: 'Canal Park Dr, Duluth, MN 55802',
        highlights: ['The Lakewalk', 'Lighthouse', 'Lift Bridge'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-4',
        type: 'adventure',
        name: 'Glensheen Mansion',
        category: 'Historic • Tours • Gardens',
        cost: '$20-$35 (Tours)',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.7',
        reviews: '8,923',
        description: 'A 39-room historic estate on Lake Superior offering tours of the home and extensive grounds.',
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
        location: 'East Duluth',
        phone: '(218) 726-8910',
        website: 'https://glensheen.org/',
        address: '3300 London Rd, Duluth, MN 55804',
        highlights: ['Full Mansion Tour', 'Gardens', 'Beach'],
        hours: {
            'Monday': '9:00 AM - 5:00 PM',
            'Tuesday': '9:00 AM - 5:00 PM',
            'Wednesday': '9:00 AM - 5:00 PM',
            'Thursday': '9:00 AM - 5:00 PM',
            'Friday': '9:00 AM - 5:00 PM',
            'Saturday': '9:00 AM - 5:00 PM',
            'Sunday': '9:00 AM - 5:00 PM'
        }
    },
    {
        id: 'explore-5',
        type: 'adventure',
        name: 'Spirit Mountain',
        category: 'Adventure • Skiing • Biking',
        cost: 'Varies ($20-$60)',
        timeNeeded: 'Spend 2-4 Hours',
        rating: '4.5',
        reviews: '6,789',
        description: 'All-season recreation area with skiing, mountain biking, and an adventure park.',
        image: 'https://images.unsplash.com/photo-1551524164-6cf77f5e1d6e?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 628-2891',
        website: 'https://spiritmt.com/',
        address: '9500 Spirit Mountain Pl, Duluth, MN 55810',
        highlights: ['Alpine Coaster', 'Zip Line', 'MTB Trails'],
        hours: {
            'Monday': 'Varies by Season',
            'Tuesday': 'Varies by Season',
            'Wednesday': 'Varies by Season',
            'Thursday': 'Varies by Season',
            'Friday': 'Varies by Season',
            'Saturday': 'Varies by Season',
            'Sunday': 'Varies by Season'
        }
    },
    {
        id: 'explore-6',
        type: 'adventure',
        name: 'Hartley Park',
        category: 'Nature • Hiking • Biking',
        cost: 'Free',
        timeNeeded: 'Spend 1-3 Hours',
        rating: '4.6',
        reviews: '3,456',
        description: 'A massive 660-acre nature center with trails for hiking, biking, and skiing.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'Woodland',
        phone: '(218) 724-6735',
        website: 'https://hartleynature.org/',
        address: '3001 Woodland Ave, Duluth, MN 55803',
        highlights: ['Old Hartley Pond', 'Rock Knob', 'Pines'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-7',
        type: 'adventure',
        name: 'Leif Erikson Park',
        category: 'Gardens • Lake Views',
        cost: 'Free',
        timeNeeded: 'Spend 30-60 Minutes',
        rating: '4.5',
        reviews: '4,567',
        description: 'Home to the Duluth Rose Garden and a replica Viking ship, right on the lake.',
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop',
        location: 'East Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '1301 London Rd, Duluth, MN 55805',
        highlights: ['Rose Garden', 'Viking Ship', 'Lake Access'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-8',
        type: 'adventure',
        name: 'Lake Superior Zoo',
        category: 'Family • Animals',
        cost: '$14 - $18',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.3',
        reviews: '5,234',
        description: 'The region\'s main zoo featuring animals from the Duluth area and around the world.',
        image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4500',
        website: 'https://lszoo.org/',
        address: '7210 Fremont St, Duluth, MN 55807',
        highlights: ['Brown Bears', 'Tigers', 'Train Ride'],
        hours: {
            'Monday': '10:00 AM - 4:00 PM',
            'Tuesday': '10:00 AM - 4:00 PM',
            'Wednesday': '10:00 AM - 4:00 PM',
            'Thursday': '10:00 AM - 4:00 PM',
            'Friday': '10:00 AM - 4:00 PM',
            'Saturday': '10:00 AM - 4:00 PM',
            'Sunday': '10:00 AM - 4:00 PM'
        }
    },
    {
        id: 'explore-9',
        type: 'adventure',
        name: 'Great Lakes Aquarium',
        category: 'Family • Marine Life',
        cost: '$16 - $20',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '7,891',
        description: 'A freshwater aquarium focusing on the ecosystem of Lake Superior and the Great Lakes.',
        image: 'https://images.unsplash.com/photo-1517783999523-9963f9953f73?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 740-3474',
        website: 'https://glaquarium.org/',
        address: '353 Harbor Dr, Duluth, MN 55802',
        highlights: ['Otter Cove', 'Sturgeon Tank', 'Touch Pools'],
        hours: {
            'Monday': '10:00 AM - 6:00 PM',
            'Tuesday': '10:00 AM - 6:00 PM',
            'Wednesday': '10:00 AM - 6:00 PM',
            'Thursday': '10:00 AM - 6:00 PM',
            'Friday': '10:00 AM - 6:00 PM',
            'Saturday': '10:00 AM - 6:00 PM',
            'Sunday': '10:00 AM - 6:00 PM'
        }
    },
    {
        id: 'explore-10',
        type: 'adventure',
        name: 'Jay Cooke State Park',
        category: 'Hiking • Waterfalls',
        cost: '$7 Day Pass',
        timeNeeded: 'Spend 2-4 Hours',
        rating: '4.8',
        reviews: '9,123',
        description: 'Famous for its swinging bridge over the St. Louis River and rugged rock formations.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Carlton (Nearby)',
        phone: '(218) 673-7000',
        website: 'https://www.dnr.state.mn.us/',
        address: '780 MN-210, Carlton, MN 55718',
        highlights: ['Swinging Bridge', 'River Gorge', 'Hiking'],
        hours: {
            'Monday': '8:00 AM - 10:00 PM',
            'Tuesday': '8:00 AM - 10:00 PM',
            'Wednesday': '8:00 AM - 10:00 PM',
            'Thursday': '8:00 AM - 10:00 PM',
            'Friday': '8:00 AM - 10:00 PM',
            'Saturday': '8:00 AM - 10:00 PM',
            'Sunday': '8:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-11',
        type: 'adventure',
        name: 'Park Point',
        category: 'Beach • Swimming',
        cost: 'Free',
        timeNeeded: 'Spend 1-3 Hours',
        rating: '4.5',
        reviews: '5,234',
        description: 'The world\'s longest freshwater sandbar, featuring a sandy beach and pine forests.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Park Point',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '45th St & Minnesota Ave, Duluth, MN 55802',
        highlights: ['Sandy Beach', 'Sand Dunes', 'Lake Views'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-12',
        type: 'adventure',
        name: 'Lincoln Park',
        category: 'Waterfalls • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '3,456',
        description: 'The namesake park of the craft district, featuring Elephant Rock and waterfalls.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'Lincoln Park',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Lincoln Park Dr, Duluth, MN 55806',
        highlights: ['Elephant Rock', 'Waterfalls', 'Trails'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-13',
        type: 'adventure',
        name: 'Chester Park (Upper)',
        category: 'Hiking • Skiing',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.5',
        reviews: '2,789',
        description: 'A favorite local park with ski jumps, hiking trails along Chester Creek, and concerts.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Chester Park',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '1800 E Skyline Pkwy, Duluth, MN 55812',
        highlights: ['Chester Creek', 'Concert Series', 'Trails'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-14',
        type: 'adventure',
        name: 'Congdon Park',
        category: 'Hiking • Waterfalls',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.6',
        reviews: '3,123',
        description: 'A rugged, beautiful hike along Tischer Creek featuring red clay paths and waterfalls.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'East Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '3200 E Superior St, Duluth, MN 55804',
        highlights: ['Tischer Creek', 'Waterfalls', 'Bridges'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-15',
        type: 'adventure',
        name: 'Lester Park',
        category: 'Hiking • Skiing • Biking',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.6',
        reviews: '4,567',
        description: 'Massive park on the east side with miles of trails and the Seven Bridges Road.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'Lester Park',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '61st Ave E & Superior St, Duluth, MN 55804',
        highlights: ['Seven Bridges Road', 'Lester River', 'Ski Trails'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-16',
        type: 'adventure',
        name: 'Ely\'s Peak',
        category: 'Hiking • Views',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.7',
        reviews: '3,890',
        description: 'A rugged hike in West Duluth featuring an abandoned railroad tunnel and panoramic views.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://superiorhikingtrail.org/',
        address: '123rd Ave W, Duluth, MN 55808',
        highlights: ['Railroad Tunnel', 'DWP Trail', 'Views'],
        hours: {
            'Monday': 'Sunrise to Sunset',
            'Tuesday': 'Sunrise to Sunset',
            'Wednesday': 'Sunrise to Sunset',
            'Thursday': 'Sunrise to Sunset',
            'Friday': 'Sunrise to Sunset',
            'Saturday': 'Sunrise to Sunset',
            'Sunday': 'Sunrise to Sunset'
        }
    },
    {
        id: 'explore-17',
        type: 'adventure',
        name: 'Brighton Beach',
        category: 'Lake Access • Picnics',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '2,345',
        description: 'A rocky stretch of shoreline perfect for skipping stones and picnics on the rocks.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'East Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '6200 London Rd, Duluth, MN 55804',
        highlights: ['Rocky Shoreline', 'Lake Views', 'Kitchi Gammi Park'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-18',
        type: 'adventure',
        name: 'Chambers Grove',
        category: 'History • River',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.3',
        reviews: '1,234',
        description: 'Historic park on the St. Louis River with a replica pavilion and canoe launch.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'Fond du Lac',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '13404 MN-23, Duluth, MN 55808',
        highlights: ['Historic Pavilion', 'River Access'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-19',
        type: 'adventure',
        name: 'Magney-Snively',
        category: 'Nature • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.5',
        reviews: '2,567',
        description: 'A hidden gem protecting old-growth forests and rugged ski trails.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Skyline Pkwy & Snively Rd, Duluth, MN 55810',
        highlights: ['Old Growth Forest', 'Rock Formations'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-20',
        type: 'adventure',
        name: 'Hawk Ridge',
        category: 'Nature • Birds',
        cost: 'Free (Donation)',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.8',
        reviews: '4,123',
        description: 'One of the best places in North America to watch hawk migrations in the fall.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'East Duluth',
        phone: '(218) 428-6209',
        website: 'https://www.hawkridge.org/',
        address: '3980 E Skyline Pkwy, Duluth, MN 55804',
        highlights: ['Bird Migration', 'Overlook', 'Hiking'],
        hours: {
            'Monday': 'Sunrise to Sunset',
            'Tuesday': 'Sunrise to Sunset',
            'Wednesday': 'Sunrise to Sunset',
            'Thursday': 'Sunrise to Sunset',
            'Friday': 'Sunrise to Sunset',
            'Saturday': 'Sunrise to Sunset',
            'Sunday': 'Sunrise to Sunset'
        }
    },
    {
        id: 'explore-21',
        type: 'adventure',
        name: 'Skyline Parkway',
        category: 'Scenic Drive • Views',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.7',
        reviews: '6,789',
        description: 'A 25-mile scenic byway that follows the ridge line above the city.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Various',
        phone: '(218) 730-4300',
        website: 'https://visitduluth.com/',
        address: 'Skyline Pkwy, Duluth, MN',
        highlights: ['Seven Bridges Rd', 'Enger Tower', 'Overlooks'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-22',
        type: 'adventure',
        name: 'Lake Superior Maritime Visitor Center',
        category: 'Museum • History',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.6',
        reviews: '8,456',
        description: 'The most visited attraction in Duluth, detailing shipping history on the lake.',
        image: 'https://images.unsplash.com/photo-1517783999523-9963f9953f73?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 720-5260',
        website: 'https://www.sa.usace.army.mil/',
        address: '600 Canal Park Dr, Duluth, MN 55802',
        highlights: ['Ship Models', 'Lift Bridge Info', 'Interactive'],
        hours: {
            'Monday': '10:00 AM - 4:30 PM',
            'Tuesday': '10:00 AM - 4:30 PM',
            'Wednesday': '10:00 AM - 4:30 PM',
            'Thursday': '10:00 AM - 4:30 PM',
            'Friday': '10:00 AM - 4:30 PM',
            'Saturday': '10:00 AM - 4:30 PM',
            'Sunday': '10:00 AM - 4:30 PM'
        }
    },
    {
        id: 'explore-23',
        type: 'adventure',
        name: 'North Shore Scenic Railroad',
        category: 'History • Tours',
        cost: '$25 - $50',
        timeNeeded: 'Spend 2-4 Hours',
        rating: '4.5',
        reviews: '3,567',
        description: 'Historic train rides that travel up the North Shore or along the river.',
        image: 'https://images.unsplash.com/photo-1517783999523-9963f9953f73?w=800&h=600&fit=crop',
        location: 'Downtown',
        phone: '(218) 722-1273',
        website: 'https://duluthtrains.com/',
        address: '506 W Michigan St, Duluth, MN 55802',
        highlights: ['Pizza Train', 'Two Harbors Trip', 'Scenic Views'],
        hours: {
            'Monday': 'Varies by Tour',
            'Tuesday': 'Varies by Tour',
            'Wednesday': 'Varies by Tour',
            'Thursday': 'Varies by Tour',
            'Friday': 'Varies by Tour',
            'Saturday': 'Varies by Tour',
            'Sunday': 'Varies by Tour'
        }
    },
    {
        id: 'explore-24',
        type: 'adventure',
        name: 'Vista Fleet',
        category: 'Tours • Boat',
        cost: '$30 - $60',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '4,234',
        description: 'Sightseeing boat cruises that tour the harbor and Lake Superior.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 722-6218',
        website: 'https://vistafleet.com/',
        address: '323 Harbor Dr, Duluth, MN 55802',
        highlights: ['Harbor Tour', 'Sunset Cruise', 'Bridge Underpass'],
        hours: {
            'Monday': 'Seasonal',
            'Tuesday': 'Seasonal',
            'Wednesday': 'Seasonal',
            'Thursday': 'Seasonal',
            'Friday': 'Seasonal',
            'Saturday': 'Seasonal',
            'Sunday': 'Seasonal'
        }
    },
    {
        id: 'explore-25',
        type: 'adventure',
        name: 'S.S. William A. Irvin',
        category: 'History • Tours',
        cost: '$15 - $20',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.5',
        reviews: '3,890',
        description: 'A massive ore boat turned museum ship that you can tour.',
        image: 'https://images.unsplash.com/photo-1517783999523-9963f9953f73?w=800&h=600&fit=crop',
        location: 'Canal Park',
        phone: '(218) 722-7876',
        website: 'https://decc.org/william-a-irvin/',
        address: '301 Harbor Dr, Duluth, MN 55802',
        highlights: ['Ship Tour', 'Engine Room', 'Haunted Ship (Oct)'],
        hours: {
            'Monday': 'Seasonal',
            'Tuesday': 'Seasonal',
            'Wednesday': 'Seasonal',
            'Thursday': 'Seasonal',
            'Friday': 'Seasonal',
            'Saturday': 'Seasonal',
            'Sunday': 'Seasonal'
        }
    },
    {
        id: 'explore-26',
        type: 'adventure',
        name: 'Wade Stadium',
        category: 'Sports • Baseball',
        cost: '$10 - $15',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.3',
        reviews: '2,123',
        description: 'Historic WPA-era baseball stadium, home of the Duluth Huskies.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 786-9909',
        website: 'https://northwoodsleague.com/',
        address: '101 N 35th Ave W, Duluth, MN 55807',
        highlights: ['Duluth Huskies', 'Historic Brick Walls'],
        hours: {
            'Monday': 'Game Days',
            'Tuesday': 'Game Days',
            'Wednesday': 'Game Days',
            'Thursday': 'Game Days',
            'Friday': 'Game Days',
            'Saturday': 'Game Days',
            'Sunday': 'Game Days'
        }
    },
    {
        id: 'explore-27',
        type: 'adventure',
        name: 'Bagley Nature Area',
        category: 'Nature • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '1,567',
        description: 'A nature preserve on the UMD campus featuring Rock Hill and camping.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'University',
        phone: '(218) 726-6134',
        website: 'https://top.d.umn.edu/',
        address: '1115 Bagley Dr, Duluth, MN 55811',
        highlights: ['Rock Hill Overlook', 'Forests'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-28',
        type: 'adventure',
        name: 'Web Woods',
        category: 'Nature • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.3',
        reviews: '987',
        description: 'A quiet, lesser-known forest trail system connecting to Hartley.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'University',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Varsity Dr, Duluth, MN 55811',
        highlights: ['Quiet Trails', 'Forest'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-29',
        type: 'adventure',
        name: 'Western Waterfront Trail',
        category: 'Hiking • Biking',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.4',
        reviews: '2,345',
        description: 'A scenic gravel trail following the St. Louis River (Waabizheshikana).',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '7300 Grand Ave, Duluth, MN 55807',
        highlights: ['River Views', 'Birding', 'Flat Trail'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-30',
        type: 'adventure',
        name: 'McQuade Small Craft Harbor',
        category: 'Water • Kayaking',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.5',
        reviews: '1,890',
        description: 'Protected harbor on the North Shore, perfect for kayaking and fishing.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'North Shore',
        phone: '(218) 723-4728',
        website: 'https://www.dnr.state.mn.us/',
        address: 'Scenic Hwy 61, Duluth, MN 55804',
        highlights: ['Breakwall', 'Safe Launch', 'Tunnel'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-31',
        type: 'adventure',
        name: 'Lakewalk',
        category: 'Walking • Biking',
        cost: 'Free',
        timeNeeded: 'Spend 1-3 Hours',
        rating: '4.7',
        reviews: '12,345',
        description: 'The paved 7-mile trail hugging the shoreline from Canal Park to Brighton Beach.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Canal Park / East',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Canal Park Dr to 60th Ave E, Duluth, MN',
        highlights: ['Lake Views', 'Boardwalk', 'Paved Trail'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-32',
        type: 'adventure',
        name: 'Seven Bridges Road',
        category: 'Scenic Drive • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.8',
        reviews: '5,678',
        description: 'A historic stone-bridge road winding up changing elevation along Amity Creek.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Lester Park',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Seven Bridges Rd, Duluth, MN 55804',
        highlights: ['Stone Bridges', 'Creek Access', 'Fall Colors'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-33',
        type: 'adventure',
        name: 'Mission Creek Trails',
        category: 'Biking • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.6',
        reviews: '2,890',
        description: 'A world-class mountain biking system with flow trails and bridges.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://coggs.com/',
        address: '1299 131st Ave W, Duluth, MN 55808',
        highlights: ['Flow Trails', 'Bridges', 'Bike Skills'],
        hours: {
            'Monday': 'Sunrise to Sunset',
            'Tuesday': 'Sunrise to Sunset',
            'Wednesday': 'Sunrise to Sunset',
            'Thursday': 'Sunrise to Sunset',
            'Friday': 'Sunrise to Sunset',
            'Saturday': 'Sunrise to Sunset',
            'Sunday': 'Sunrise to Sunset'
        }
    },
    {
        id: 'explore-34',
        type: 'adventure',
        name: 'Piedmont Trail System',
        category: 'Biking • Hiking',
        cost: 'Free',
        timeNeeded: 'Spend 2-3 Hours',
        rating: '4.7',
        reviews: '3,456',
        description: 'Famous technical mountain biking trails with huge views over the harbor.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://coggs.com/',
        address: '2306 W Skyline Pkwy, Duluth, MN 55806',
        highlights: ['Harbor Views', 'Technical Rock Riding'],
        hours: {
            'Monday': 'Sunrise to Sunset',
            'Tuesday': 'Sunrise to Sunset',
            'Wednesday': 'Sunrise to Sunset',
            'Thursday': 'Sunrise to Sunset',
            'Friday': 'Sunrise to Sunset',
            'Saturday': 'Sunrise to Sunset',
            'Sunday': 'Sunrise to Sunset'
        }
    },
    {
        id: 'explore-35',
        type: 'adventure',
        name: 'Gichi-ode\' Akiing',
        category: 'Gathering • Views',
        cost: 'Free',
        timeNeeded: 'Spend 30-60 Minutes',
        rating: '4.4',
        reviews: '2,123',
        description: 'Lake Place Park - a park built over the freeway connecting downtown to the lake.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Downtown',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '200 E Superior St, Duluth, MN 55802',
        highlights: ['Lake Views', 'Art', 'Connection to Lakewalk'],
        hours: {
            'Monday': 'Open 24 hours',
            'Tuesday': 'Open 24 hours',
            'Wednesday': 'Open 24 hours',
            'Thursday': 'Open 24 hours',
            'Friday': 'Open 24 hours',
            'Saturday': 'Open 24 hours',
            'Sunday': 'Open 24 hours'
        }
    },
    {
        id: 'explore-36',
        type: 'adventure',
        name: 'Brewer Park',
        category: 'Hiking • Views',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.3',
        reviews: '1,234',
        description: 'Features the "Bi-to-Bi" trail and great views from the bluffs.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: 'Hwy 2 & 70th Ave W, Duluth, MN 55807',
        highlights: ['Bluff Views', 'Hiking Trails'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-37',
        type: 'adventure',
        name: 'Fairmont Park',
        category: 'Community • Family',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.2',
        reviews: '987',
        description: 'Adjacent to the Zoo, featuring trails and community space.',
        image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '7210 Fremont St, Duluth, MN 55807',
        highlights: ['Quiet Trails', 'Zoo Access'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-38',
        type: 'adventure',
        name: 'Memorial Park',
        category: 'Sports • Community',
        cost: 'Free',
        timeNeeded: 'Spend 1-2 Hours',
        rating: '4.2',
        reviews: '1,456',
        description: 'Large park with athletic fields and winter skating rinks.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'West Duluth',
        phone: '(218) 730-4300',
        website: 'https://duluthmn.gov/parks/',
        address: '501 N 54th Ave W, Duluth, MN 55807',
        highlights: ['Hockey Rink', 'Baseball Fields'],
        hours: {
            'Monday': '6:00 AM - 10:00 PM',
            'Tuesday': '6:00 AM - 10:00 PM',
            'Wednesday': '6:00 AM - 10:00 PM',
            'Thursday': '6:00 AM - 10:00 PM',
            'Friday': '6:00 AM - 10:00 PM',
            'Saturday': '6:00 AM - 10:00 PM',
            'Sunday': '6:00 AM - 10:00 PM'
        }
    },
    {
        id: 'explore-39',
        type: 'adventure',
        name: 'Pattison State Park',
        category: 'Hiking • Waterfalls',
        cost: '$11 Vehicle Pass',
        timeNeeded: 'Spend 2-4 Hours',
        rating: '4.7',
        reviews: '4,567',
        description: 'Wisconsin state park featuring Big Manitou Falls, the highest in WI.',
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
        location: 'Superior, WI (Nearby)',
        phone: '(715) 399-3111',
        website: 'https://dnr.wisconsin.gov/',
        address: '6294 S State Rd 35, Superior, WI 54880',
        highlights: ['Big Manitou Falls', 'Little Manitou Falls'],
        hours: {
            'Monday': '6:00 AM - 11:00 PM',
            'Tuesday': '6:00 AM - 11:00 PM',
            'Wednesday': '6:00 AM - 11:00 PM',
            'Thursday': '6:00 AM - 11:00 PM',
            'Friday': '6:00 AM - 11:00 PM',
            'Saturday': '6:00 AM - 11:00 PM',
            'Sunday': '6:00 AM - 11:00 PM'
        }
    },
    {
        id: 'explore-40',
        type: 'adventure',
        name: 'Wisconsin Point',
        category: 'Beach • Nature',
        cost: 'Free',
        timeNeeded: 'Spend 1-3 Hours',
        rating: '4.5',
        reviews: '3,234',
        description: 'Long sandbar in Superior, WI with a lighthouse and bird watching.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
        location: 'Superior, WI (Nearby)',
        phone: '(715) 395-7270',
        website: 'https://www.ci.superior.wi.us/',
        address: 'Wisconsin Point Rd, Superior, WI 54880',
        highlights: ['Superior Entry Lighthouse', 'Beach'],
        hours: {
            'Monday': '6:00 AM - 11:00 PM',
            'Tuesday': '6:00 AM - 11:00 PM',
            'Wednesday': '6:00 AM - 11:00 PM',
            'Thursday': '6:00 AM - 11:00 PM',
            'Friday': '6:00 AM - 11:00 PM',
            'Saturday': '6:00 AM - 11:00 PM',
            'Sunday': '6:00 AM - 11:00 PM'
        }
    }
];
